package:
  format-version: "1.0.0"
  name: "bootloader_apps_sam_d20"
  version: "3.0.0"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "bootloader"
      type: "package"
      version: "3.6.0"


